#!/bin/sh
DIR=$(dirname "$0")
export LD_LIBRARY_PATH="${DIR}"
exec "${DIR}/JavaApplicationStub" "$@" &
sleep 10
mkdir -p "${DIR}/../Resources/Chrome"
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
  --app=http://localhost:8080 \
  --user-data-dir="${DIR}/../Resources/Chrome" &
